//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Description&quot;: &quot;Give points for answers longer than 5 chars&quot;,
        ///    &quot;Condition&quot;: {
        ///      &quot;Property&quot;: &quot;Title.Length&quot;,
        ///      &quot;LogicalOp&quot;: &quot;GreaterThan&quot;,
        ///      &quot;Value&quot;: 5
        ///    },
        ///    &quot;Reaction&quot;: {
        ///      &quot;PointsModifier&quot;: 5,
        ///      &quot;Message&quot;: &quot;Not a short title&quot;
        ///    }
        ///  },
        ///  {
        ///    &quot;Description&quot;: &quot;Don&apos;t sit on the fence (no opinion, negative or positive)&quot;,
        ///    &quot;Condition&quot;: {
        ///      &quot;Property&quot;: &quot;ReactionToParent.AgreeWithParent&quot;,
        ///      &quot;LogicalOp&quot;: &quot;equals&quot;,
        ///      &quot;Value&quot;: null
        ///    },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RatingRules {
            get {
                return ResourceManager.GetString("RatingRules", resourceCulture);
            }
        }
    }
}
