// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ContosoCarsML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Accepted"), LoadColumn(1)]
        public string Accepted { get; set; }


        [ColumnName("Filename"), LoadColumn(2)]
        public string Filename { get; set; }


        [ColumnName("keywords"), LoadColumn(3)]
        public string Keywords { get; set; }


    }
}
